/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: f6db303666caeef8b9e801701d426513)
interface __BaseEnv_Env {
	YOUTUBE_API_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "YOUTUBE_API_KEY">> {}
}
