/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: a4b4a9e085ffb1a1e7829c34f714c2e8)
interface __BaseEnv_Env {
	SNAPSHOT_KV: KVNamespace;
	YOUTUBE_API_KEY: string;
	DATABASE_URL: string;
	REPORT_CODE: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "YOUTUBE_API_KEY" | "DATABASE_URL" | "REPORT_CODE">> {}
}
